package tech.bugger.control.backing;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import tech.bugger.business.internal.ApplicationSettings;
import tech.bugger.business.util.MarkdownHandler;

/**
 * Backing Bean for the imprint page.
 */
@RequestScoped
@Named
public class ImprintBacker {

    /**
     * The current application settings.
     */
    private final ApplicationSettings settings;

    /**
     * Constructs a new imprint page backing bean with the necessary dependencies.
     *
     * @param settings The application settings to use.
     */
    @Inject
    public ImprintBacker(final ApplicationSettings settings) {
        this.settings = settings;
    }

    /**
     * Returns the imprint as an HTML-String as generated by the {@link MarkdownHandler}.
     *
     * @return The imprint.
     */
    public String getImprint() {
        String policy = settings.getOrganization().getImprint();

        if (policy == null) {
            return "";
        } else {
            return MarkdownHandler.toHtml(policy);
        }
    }

}
