package tech.bugger.control.backing;

import tech.bugger.business.internal.ApplicationSettings;
import tech.bugger.global.util.Log;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * Backing Bean for the imprint page.
 */
@RequestScoped
@Named
public class ImprintBacker {

    private static final Log log = Log.forClass(ImprintBacker.class);

    @Inject
    private ApplicationSettings settings;

    /**
     * Returns the imprint as an HTML-String as generated by the {@code MarkdownHandler}.
     *
     * @return The imprint.
     */
    public String getImprint() {
        return null;
    }

}
