package tech.bugger.control.backing;

import tech.bugger.business.internal.ApplicationSettings;
import tech.bugger.global.util.Log;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 * Backing bean for the privacy policy page.
 */
@RequestScoped
@Named
public class PrivacyBacker {

    private static final Log log = Log.forClass(PrivacyBacker.class);

    @Inject
    private ApplicationSettings settings;

    /**
     * Returns the privacy policy as an HTML-String as generated by the {@code MarkdownHandler}.
     *
     * @return The privacy policy.
     */
    public String getPrivacyPolicy() {
        return null;
    }

}
