package tech.bugger.control.backing;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import tech.bugger.business.internal.ApplicationSettings;
import tech.bugger.business.util.MarkdownHandler;

/**
 * Backing bean for the privacy policy page.
 */
@RequestScoped
@Named
public class PrivacyBacker {

    /**
     * The current application settings.
     */
    private final ApplicationSettings settings;

    /**
     * Constructs a new privacy policy page backing bean with the necessary dependencies.
     *
     * @param settings The application settings to use.
     */
    @Inject
    public PrivacyBacker(final ApplicationSettings settings) {
        this.settings = settings;
    }

    /**
     * Returns the privacy policy as an HTML-String as generated by the {@link MarkdownHandler}.
     *
     * @return The privacy policy.
     */
    public String getPrivacyPolicy() {
        String policy = settings.getOrganization().getPrivacyPolicy();

        if (policy == null) {
            return "";
        } else {
            return MarkdownHandler.toHtml(policy);
        }
    }

}
