package tech.bugger.control.backing;

import javax.enterprise.context.RequestScoped;
import javax.inject.Inject;
import javax.inject.Named;
import tech.bugger.business.internal.ApplicationSettings;
import tech.bugger.global.util.Log;

/**
 * Backing bean for the privacy policy page.
 */
@RequestScoped
@Named
public class PrivacyBacker {

    /**
     * The {@link Log} instance associated with this class for logging purposes.
     */
    private static final Log log = Log.forClass(PrivacyBacker.class);

    /**
     * The current application settings.
     */
    private final ApplicationSettings settings;

    /**
     * Constructs a new privacy policy page backing bean with the necessary dependencies.
     *
     * @param settings The application settings to use.
     */
    @Inject
    public PrivacyBacker(final ApplicationSettings settings) {
        this.settings = settings;
    }

    /**
     * Returns the privacy policy as an HTML-String as generated by the {@code MarkdownHandler}.
     *
     * @return The privacy policy.
     */
    public String getPrivacyPolicy() {
        return null;
    }

}
